version: "1.0"
info:
  model: int-scaffold
packages:
- name: JC_TestNextProject
  gitServerName: JC_TEST
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitBranch: main
services:
- serviceName: project.jc_testnext.integrations:HelloAgain
  packages:
  - name: JC_TestNextProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.1962
